run = "npm run dev"
modules = ["nodejs-20", "python-3.11"]

[nix]
channel = "stable-24_05"

[deployment]
run = ["sh", "-c", "npm run dev"]
deploymentTarget = "cloudrun"

[[ports]]
localPort = 5000
externalPort = 80